FROM almalinux:9
EXPOSE 80/tcp 
#port that this container listen at runtime. just for information nginx running 80 eg: backend is running 8080.
#if other user wants to inspect our image id cmd: docker inspect <image id> then they get this info....