FROM run:1.0
CMD ["nginx","-g","daemon off;"]
LABEL author="nirmala" \
      course="Devops" \
      description="I am working on docker project"

      # sample2: push and pull images into dockerhub. 
      # for push: cmd:  docker push nirmaladevops12/label:1.0

      # retag the imagename: cmd: docker tag label:1.0 nirmaladevops12/label:1.0
      #docker images( it will shows the renamed image name)

      # push again cmd: docker push nirmaladevops12/label:1.0

      # login required: username:nirmaladevops12 pwd:Nirmala@2024

      # push again

      # check into the dockerhub.com.....repository(it will show)

      # for pull:
            # docker pull nirmaladevops12/label:1.0
